SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER trig 
AFTER INSERT 
ON Parent1
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Parent1');
END;
/

CREATE OR REPLACE TRIGGER trig2 
AFTER INSERT 
ON Male1
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Male1');
END;
/

CREATE OR REPLACE TRIGGER trig3 
AFTER INSERT 
ON Female1
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Female1');
END;
/