SET SERVEROUTPUT ON;
CREATE OR REPLACE TRIGGER trig 
AFTER INSERT 
ON Parent2
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Parent2');
END;
/

CREATE OR REPLACE TRIGGER trig2 
AFTER INSERT 
ON Male2
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Male2');
END;
/

CREATE OR REPLACE TRIGGER trig3 
AFTER INSERT 
ON Female2
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Value inserted on Female2');
END;
/