SET SERVEROUTPUT ON;

CREATE OR REPLACE PACKAGE mypack AS
	PROCEDURE FindGrandParent(S IN VARCHAR2);
	PROCEDURE FindGrandChildren(S IN VARCHAR2);
	PROCEDURE FindGrandBrother(S IN VARCHAR2);
	PROCEDURE FindGrandSister(S IN VARCHAR2);
	PROCEDURE FindGrandUncle(S IN VARCHAR2);
	PROCEDURE FindGrandAunt(S IN VARCHAR2);
END mypack;
/
commit;